### ISSUE TITLE
fail to open file 'None'

### ISSUE THREAD

**Issue by animesh** [uio-bmi/two_step_graph_mapper#2]
Trying to https://github.com/uio-bmi/two_step_graph_mapper#reproducing-the-results-from-the-manuscript-thorough-benchmarking-on-whole-genome-1000-genomes-graph but facing the following errror:

```
root@a01bb382c193:~# ../run_benchmark.sh None $simulation_data_dir/hg19_chr1-Y.fa None $graph_dir/wg $simulation_data_dir/haplotype0_only_chr20_no_paths $simulation_data_dir/haplotype1_only_chr20_no_paths \
>     $simulation_data_dir/giab $simulation_data_dir/giab_only_reference $threads "--forward-only -n 5000000 -e 0.01 -i 0.002 -l 150" 2358792 150 "" \
>     $graph_dir 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X None None None None 20 63025520 $graph_dir/hisat2_index None None
bash: ../run_benchmark.sh: No such file or directory
root@a01bb382c193:~# ../run_benchmark.sh None $simulation_data_dir/hg19_chr1-Y.fa None $graph_dir/wg $simulation_data_dir/haplotype0_only_chr20_no_paths $simulation_data_dir/haplotype1_only_chr20_no_paths     $simulation_data_dir/giab $simulation_data_dir/giab_only_reference $threads "--forward-only -n 5000000 -e 0.01 -i 0.002 -l 150" 2358792 150 ""     $graph_dir 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X None None None None 20 63025520 $graph_dir/hisat2_index None None
bash: ../run_benchmark.sh: No such file or directory
root@a01bb382c193:~# /data/two_step_graph_mapper/benchmarking/run_benchmark.sh None $simulation_data_dir/hg19_chr1-Y.fa None $graph_dir/wg $simulation_data_dir/haplotype0_only_chr20_no_paths $simulation_data_dir/haplotype1_only_chr20_no_
paths     $simulation_data_dir/giab $simulation_data_dir/giab_only_reference $threads "--forward-only -n 5000000 -e 0.01 -i 0.002 -l 150" 2358792 150 ""     $graph_dir 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X None None
None None 20 63025520 $graph_dir/hisat2_index None None
/data/data/giab.xg None.xg /data/data/wg.xg
Filter variants
[E::hts_hopen] fail to open file 'None'
[E::hts_open_format] fail to open file 'None'
Traceback (most recent call last):
  File "/usr/local/bin/mitty", line 11, in <module>
    load_entry_point('mitty==2.28.3', 'console_scripts', 'mitty')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mitty/cli.py", line 36, in filter_vcf
    mvio.prepare_variant_file(vcfin, sample, bed, vcfout)
  File "/usr/local/lib/python3.6/dist-packages/mitty/lib/vcfio.py", line 221, in prepare_variant_file
    vcf_in = pysam.VariantFile(fname_in, mode)
  File "pysam/libcbcf.pyx", line 3479, in pysam.libcbcf.VariantFile.__init__ (pysam/libcbcf.c:51398)
  File "pysam/libcbcf.pyx", line 3666, in pysam.libcbcf.VariantFile.open (pysam/libcbcf.c:53994)
ValueError: could not open file `b'None'` (mode='b'r'') - is it VCF/BCF format?
r
```

**Comment by ivargr** [comment]
Hi!

Sorry, there seems to be a file name missing from the command in the Readme.

Can you try this command instead?

```
../run_benchmark.sh None $simulation_data_dir/hg19_chr1-Y.fa None $graph_dir/wg $simulation_data_dir/haplotype0_only_chr20_no_paths $simulation_data_dir/haplotype1_only_chr20_no_paths \
    $simulation_data_dir/giab $simulation_data_dir/giab_only_reference $threads "--forward-only -n 5000000 -e 0.01 -i 0.002 -l 150" 2358792 150 "" \
    $graph_dir 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X $simulation_data_dir/giab_chr20.nobg  giab_reference_path_20.intervalcollection.indexed \
    None $simulation_data_dir/variants.vcf.gz 20 63025520 $graph_dir/hisat2_index None None
```

I've also updated the readme with that command, which I think should work. Let me know if i doesn't.

Thanks for letting us know!
